const $=id=>document.getElementById(id);
let attachedText='', attachedName='', running=false, runs=0, totalSteps=0, lastResult=null, approvalDecision='';
const demoInvoice={vendor:'Northstar Office Supplies',invoiceNumber:'NS-2048',invoiceDate:'2026-10-08',dueDate:'2026-10-22',currency:'INR',subtotal:'₹12,000.00',tax:'₹2,160.00',total:'₹14,160.00',poNumber:'',paymentTerms:'Net 14'};
function toast(msg){const t=$('toast');t.textContent=msg;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',3000)}
function timeNow(){return new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function logEvent(title,desc,type='info'){const log=$('log');if(log.querySelector('.result-empty'))log.innerHTML='';const row=document.createElement('div');row.className='log-item '+type;row.innerHTML=`<div class="log-time">${timeNow()}</div><div><b><span class="log-dot"></span>${escapeHtml(title)}</b><p>${escapeHtml(desc)}</p></div>`;log.prepend(row)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setAgent(name,state){const el=document.querySelector(`[data-agent="${name}"]`);if(el){el.classList.remove('active','done','fail');if(state)el.classList.add(state)}}
function setProgress(p,msg){$('progress').style.width=p+'%';$('progressText').textContent=p+'%';$('runStatus').textContent=msg}
function loadDemo(){attachedText='';attachedName='Demo invoice data';$('fileInput').value='';$('fileStatus').textContent='Demo invoice loaded: NS-2048 · Northstar Office Supplies · one required field intentionally missing.';$('workflowType').value='invoice';$('instruction').value='Review this invoice, extract the key fields, check required information, and flag anything missing before approval.';toast('Demo invoice loaded');}
function parseText(text){const out={...demoInvoice};const patterns={vendor:/vendor\s*[:,-]\s*(.+)/i,invoiceNumber:/invoice(?:\s*(?:number|no\.?|#))?\s*[:,-]\s*([A-Z0-9-]+)/i,invoiceDate:/invoice date\s*[:,-]\s*([^\n,]+)/i,dueDate:/due date\s*[:,-]\s*([^\n,]+)/i,poNumber:/(?:purchase order|po number|po#)\s*[:,-]\s*([^\n,]+)/i,total:/(?:grand total|total amount|total)\s*[:,-]\s*([^\n]+)/i};for(const [k,re] of Object.entries(patterns)){const m=text.match(re);if(m)out[k]=m[1].trim()}return out}
function showResults(data,issues,type){lastResult={data,issues,type};$('resultTag').textContent=issues.length?'NEEDS REVIEW':'VALIDATED';$('resultArea').className='';$('resultArea').innerHTML='';const banner=document.createElement('div');banner.className='banner '+(issues.length?'warn':'ok');banner.textContent=issues.length?`${issues.length} validation issue${issues.length>1?'s':''} found. Review the highlighted fields before approval.`:'All required fields passed the prototype validation checks.';$('resultArea').appendChild(banner);const grid=document.createElement('div');grid.className='result-grid';const fields=[['Vendor',data.vendor],['Invoice number',data.invoiceNumber],['Invoice date',data.invoiceDate],['Due date',data.dueDate],['Subtotal',data.subtotal],['Tax',data.tax],['Total',data.total],['PO number',data.poNumber]];fields.forEach(([label,val])=>{const div=document.createElement('div');div.className='result-field '+(!String(val||'').trim()?'missing':'');div.innerHTML=`<span>${escapeHtml(label)}</span><strong>${escapeHtml(String(val||'Missing'))}</strong>`;grid.appendChild(div)});$('resultArea').appendChild(grid);const foot=document.createElement('p');foot.className='note';foot.style.marginTop='12px';foot.textContent='Demo rule: vendor, invoice number, invoice date, total, and PO number are required. This is a prototype validation, not accounting advice.';$('resultArea').appendChild(foot);
$('approvalArea').innerHTML='';if(type==='approval'){const box=document.createElement('div');box.className='approval';box.innerHTML='<h4>Human approval required</h4><p>Review the workflow result, then record an approval decision. This action is local to the demo.</p><div class="button-row"><button class="primary" id="approveBtn">Approve request</button><button class="danger" id="rejectBtn">Reject request</button></div><div id="approvalStatus" class="approval-status"></div>';$('approvalArea').appendChild(box);$('approveBtn').onclick=()=>decideApproval('Approved');$('rejectBtn').onclick=()=>decideApproval('Rejected')}
$('metricIssues').textContent=issues.length;$('metricApproval').textContent=type==='approval'?'Pending':'Not needed'}
function decideApproval(decision){approvalDecision=decision;$('approvalStatus').textContent=`Decision recorded: ${decision}`;$('approveBtn').disabled=true;$('rejectBtn').disabled=true;logEvent('Human decision recorded',`${decision} by demo user. No external system was changed.`,decision==='Approved'?'success':'warning');$('metricApproval').textContent=decision;toast(`Request ${decision.toLowerCase()}`)}
async function runWorkflow(){if(running)return;running=true;$('runBtn').disabled=true;$('runTopBtn').disabled=true;$('pipelineTag').textContent='RUNNING';$('resultTag').textContent='PROCESSING';$('approvalArea').innerHTML='';$('resultArea').className='result-empty';$('resultArea').innerHTML='<strong>Workflow in progress…</strong>Agents are processing the request.';$('log').innerHTML='';document.querySelectorAll('.agent').forEach(e=>e.classList.remove('active','done','fail'));setProgress(0,'Preparing workflow');logEvent('Workflow started','Instruction received and execution plan initialized.');const names=['Planner','Parser','Executor','Validator','Recovery'];const messages=[
['Plan created','Instruction converted into an ordered sequence of safe steps.'],
['Fields extracted','Prototype parser prepared structured invoice fields.'],
['Workflow executed','Processing completed using local demo/sample data.'],
['Validation complete','Required fields and basic data presence were checked.'],
['Recovery check complete','Safe retry policy evaluated; unresolved values remain flagged.']
];let data;const type=$('workflowType').value;const retries=Number($('recovery').value);
for(let i=0;i<names.length;i++){const n=names[i];setAgent(n,'active');setProgress(Math.round(i/5*100),`${n} agent running`);await new Promise(r=>setTimeout(r,430));if(i===1){if(attachedText){data=parseText(attachedText)}else{data={...demoInvoice}}if(type==='document'&&!attachedText){data={vendor:'Example Document',invoiceNumber:'DOC-001',invoiceDate:'2026-10-09',dueDate:'',subtotal:'',tax:'',total:'',poNumber:'',paymentTerms:''}}}
if(i===3){const required=['vendor','invoiceNumber','invoiceDate','total','poNumber'];let issues=required.filter(k=>!String(data[k]||'').trim());if(issues.length&&retries>0){logEvent('Recovery triggered',`Attempting ${retries} safe retry ${retries===1?'':'ies'} for missing fields: ${issues.join(', ')}.`, 'warning');await new Promise(r=>setTimeout(r,300));logEvent('Recovery result','No source value was available to safely fill the missing fields; no data was invented.','warning')}data._issues=issues;}
setAgent(n,'done');totalSteps++;$('metricSteps').textContent=totalSteps;logEvent(messages[i][0],messages[i][1],i===3&&data._issues.length?'warning':'success');setProgress(Math.round((i+1)/5*100),i===4?'Workflow finished':'Completed '+(i+1)+' of 5 agents')}
const issues=data._issues||[];if(type==='approval'){logEvent('Approval gate reached','Workflow paused for a human decision.','warning')}else{logEvent('Workflow finished',issues.length?'Completed with validation warnings.':'Completed successfully.',issues.length?'warning':'success')}
showResults(data,issues,type);runs++;$('metricRuns').textContent=runs;$('pipelineTag').textContent='COMPLETE';setProgress(100,issues.length?'Complete · review required':'Complete');running=false;$('runBtn').disabled=false;$('runTopBtn').disabled=false;toast('Workflow completed');}
$('demoBtn').onclick=loadDemo;$('demoBtn2').onclick=loadDemo;$('runBtn').onclick=runWorkflow;$('runTopBtn').onclick=runWorkflow;
$('clearBtn').onclick=()=>{$('log').innerHTML='<div class="result-empty"><strong>Activity log cleared</strong>New workflow events will appear here.</div>';toast('Activity log cleared')};
$('resetBtn').onclick=()=>{if(running)return;attachedText='';attachedName='';lastResult=null;approvalDecision='';runs=0;totalSteps=0;$('metricRuns').textContent='0';$('metricSteps').textContent='0';$('metricIssues').textContent='—';$('metricApproval').textContent='Not needed';$('fileInput').value='';$('fileStatus').textContent='No file attached. You can use the built-in demo data to try the workflow.';$('log').innerHTML='<div class="result-empty"><strong>No workflow activity yet</strong>Run the demo to see the agents work and record their actions here.</div>';$('resultArea').className='result-empty';$('resultArea').innerHTML='<strong>Your results will appear here</strong>Run a workflow to view extracted invoice fields, missing information, and validation status.';$('approvalArea').innerHTML='';document.querySelectorAll('.agent').forEach(e=>e.classList.remove('active','done','fail'));$('pipelineTag').textContent='READY';$('resultTag').textContent='WAITING';setProgress(0,'Ready to run');toast('Workspace reset')};
$('fileInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f){attachedText='';attachedName='';$('fileStatus').textContent='No file attached.';return}attachedName=f.name;if(f.size>2*1024*1024){$('fileStatus').textContent='File is larger than 2 MB. Please choose a smaller demo file.';e.target.value='';return}if(/\.(txt|csv|json)$/i.test(f.name)){attachedText=await f.text();$('fileStatus').textContent=`Attached: ${f.name} · ${(f.size/1024).toFixed(1)} KB · text will be parsed locally.`}else if(/\.pdf$/i.test(f.name)){attachedText='';$('fileStatus').textContent=`Attached: ${f.name}. PDF is registered for the demo, but PDF text extraction requires the backend integration; use demo data or a TXT/CSV sample to test parsing.`}else{attachedText=await f.text();$('fileStatus').textContent=`Attached: ${f.name} · local text parsing enabled.`}});
